AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Edit Heading WebSocket Module

Parameters:
  WebSocketApiId:
    Type: String
  ApiGatewayRoleArn:
    Type: String
  EditHeadingFunctionArn:
    Type: String

Resources:
  EditHeadingIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiId
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EditHeadingFunctionArn}/invocations
        - EditHeadingFunctionArn: !ImportValue EditHeadingFunctionArn
      CredentialsArn: !Ref ApiGatewayRoleArn
      IntegrationMethod: POST

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiId
      RouteKey: "$connect"
      Target: !Sub "integrations/${EditHeadingIntegration}"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiId
      RouteKey: "$disconnect"
      Target: !Sub "integrations/${EditHeadingIntegration}"

  EditHeadingRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiId
      RouteKey: "editHeading"
      Target: !Sub "integrations/${EditHeadingIntegration}"

Outputs:
  EditHeadingRoutesAdded:
    Value: "edit-heading websocket routes added"
