AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main WebSocket API for CAMMI (Shared Stage + Log Group)

Resources:
  CAMMIWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: CAMMI-WebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${CAMMIWebSocketApi}-access-logs
      RetentionInDays: 14

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - EditHeadingNestedStack  # add more stacks later
    Properties:
      ApiId: !Ref CAMMIWebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: CAMMIWebSocketDeployment
    Properties:
      StageName: dev
      Description: dev Stage with tracing enabled
      ApiId: !Ref CAMMIWebSocketApi
      DeploymentId: !Ref CAMMIWebSocketDeployment
      AccessLogSettings:
        DestinationArn: !GetAtt WebSocketLogGroup.Arn
        Format: |
          {"requestId":"$context.requestId","requestTime":"$context.requestTime","routeKey":"$context.routeKey","status":"$context.status","connectionId":"$context.connectionId"}
      DefaultRouteSettings:
        DataTraceEnabled: true
        LoggingLevel: INFO
        DetailedMetricsEnabled: true

  EditHeadingNestedStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: edit-heading.yaml
      Parameters:
        WebSocketApiId: !Ref CAMMIWebSocketApi
        ApiGatewayRoleArn: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        EditHeadingFunctionArn: !ImportValue EditHeadingFunctionArn

Outputs:
  CAMMIWebSocketApiId:
    Description: Main API ID
    Value: !Ref CAMMIWebSocketApi
    Export:
      Name: CAMMI-WebSocketApiId

  CAMMIWebSocketEndpoint:
    Description: Shared WebSocket Endpoint
    Value: !Sub "wss://${CAMMIWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Export:
      Name: CAMMI-WebSocketEndpoint
