AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Wordpress feature for CAMMI

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name imported from parent stack

Resources:
  ############################################
  # WordpressRegistrationOnCammiFunction
  ############################################
  WordpressRegistrationOnCammiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: wordpress-registration-on-cammi
      Handler: app.lambda_handler
      CodeUri: src/wordpress-registration-on-cammi/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Registers WordPress sites in DynamoDB (WordpressSites table)
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          WORDPRESS_SITES_TABLE: !ImportValue CAMMI-WordpressSitesTableName  

  ############################################
  # WordpressSchedularCammiFunction
  ############################################
  WordpressSchedularCammiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: wordpress-schedular-cammi
      Handler: app.lambda_handler
      CodeUri: src/wordpress-schedular-cammi/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Schedules posts, uploads images to S3, creates EventBridge schedules
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          WORDPRESS_SITES_TABLE: !ImportValue CAMMI-WordpressSitesTableName
          WORDPRESS_POSTS_TABLE: !ImportValue CAMMI-WordpressPostsTableName
          S3_BUCKET_NAME: !Ref S3BucketName

  ############################################
  # EventbridgeTriggeredWordpressSchedularCammiFunction
  ############################################
  EventbridgeTriggeredWordpressSchedularCammiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eventbridge-triggered-wordpress-schedular-cammi
      Handler: app.lambda_handler
      CodeUri: src/eventbridge-triggered-wordpress-schedular-cammi/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Executes scheduled posts, downloads images from S3, uploads to Wordpress
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          WORDPRESS_SITES_TABLE: !ImportValue CAMMI-WordpressSitesTableName
          WORDPRESS_POSTS_TABLE: !ImportValue CAMMI-WordpressPostsTableName
          S3_BUCKET_NAME: !Ref S3BucketName 

Outputs:
  WordpressRegistrationOnCammiFunctionArn:
    Description: ARN of WordpressRegistrationOnCammiFunction Lambda
    Value: !GetAtt WordpressRegistrationOnCammiFunction.Arn
    Export:
      Name: WordpressRegistrationOnCammiFunctionArn

  WordpressSchedularCammiFunctionArn:
    Description: ARN of WordpressSchedularCammiFunction Lambda
    Value: !GetAtt WordpressSchedularCammiFunction.Arn    

  EventbridgeTriggeredWordpressSchedularCammiFunctionArn:
    Description: ARN of EventbridgeTriggeredWordpressSchedularCammiFunction Lambda
    Value: !GetAtt EventbridgeTriggeredWordpressSchedularCammiFunction.Arn   
