AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI Feedback

# --------------------------
# API Gateway → Lambda Invoke Role
# --------------------------
Resources:
  ApiGatewayFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  ApiGatewayFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cammiApiGatewayFunctionPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "lambda:*"
            Resource: "*"
      Roles:
        - !Ref ApiGatewayFunctionRole

Outputs:
  ApiGatewayFunctionRoleArn:
    Description: "ARN of the API Gateway Lambda Invoke Role"
    Value: !GetAtt ApiGatewayFunctionRole.Arn
    Export:
      Name: CAMMI-ApiGatewayFunctionRoleArn
