AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Common Lambda feature for CAMMI

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name imported from parent stack

Resources:
  ###################################################
  # S3 to Frontend Lambda
  ###################################################
  S3ToFrontendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-to-frontend
      Handler: app.lambda_handler
      CodeUri: src/s3-to-frontend/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles S3 to gateway
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  ###################################################
  # Request to Review Documents Lambda
  ###################################################
  RequestToReviewDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: request-to-review-documents
      Handler: app.lambda_handler
      CodeUri: src/request-to-review-documents/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles add review documents
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-OrganizationsTableName
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName
          REVIEW_DOCUMENTS_TABLE: !ImportValue CAMMI-ReviewDocumentsTableName

  ###################################################
  # State Machine Starter Lambda
  ###################################################
  StateMachineStarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: state-machine-starter
      Handler: app.lambda_handler
      CodeUri: src/state-machine-starter/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles api_request_func
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:                    # ✅ FIXED — added `Variables:`
          S3_BUCKET_NAME: !Ref S3BucketName
          CLAUDE_USAGE_LOGS_TABLE: !ImportValue CAMMI-ClaudeUsageLogsTableName

  ###################################################
  # Documentation Lambda
  ###################################################
  DocumentationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: documentation
      Handler: app.lambda_handler
      CodeUri: src/documentation/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 1024
      Tracing: Active
      Description: Handles marketing_strategy_doc_generation
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Layers:
        - !ImportValue DocLibrariesLayer1Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          DOCUMENTS_HISTORY_TABLE: !ImportValue CAMMI-DocumentsHistoryTableName

  ###################################################
  # Generation Complete Function
  ###################################################
  GenerationCompleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: generation-complete
      Handler: app.lambda_handler
      CodeUri: src/generation-complete/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 1024
      Tracing: Active
      Description: Handles doc_edit_complete
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          WEBSOCKET_ENDPOINT: "{{resolve:secretsmanager:cammi-secrets:SecretString:WEBSOCKET_ENDPOINT}}" 

  GtmSubDocsCreatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: gtm-sub-docs-creator
      Handler: app.lambda_handler
      CodeUri: src/gtm-sub-docs-creator/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 1024
      Tracing: Active
      Description: Handles doc_edit_complete with multiple small docs
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          DOCUMENTS_HISTORY_TABLE: !ImportValue CAMMI-DocumentsHistoryTableName
          S3_BUCKET_NAME: !Ref S3BucketName

  DownloadAsPDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: download-as-pdf
      Handler: app.lambda_handler
      CodeUri: src/download-as-pdf/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles s3_to_gateway_pdf
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          CONVERTAPI_KEY: "{{resolve:secretsmanager:cammi-secrets:SecretString:CONVERTAPI_KEY}}" 

###################################################
# Outputs
###################################################
Outputs:
  S3ToFrontendFunctionArn:
    Description: ARN of S3ToFrontendFunction Lambda
    Value: !GetAtt S3ToFrontendFunction.Arn
    Export:
      Name: S3ToFrontendFunctionArn

  RequestToReviewDocumentsFunctionArn:
    Description: ARN of RequestToReviewDocumentsFunction Lambda
    Value: !GetAtt RequestToReviewDocumentsFunction.Arn
    Export:
      Name: RequestToReviewDocumentsFunctionArn

  StateMachineStarterFunctionArn:
    Description: ARN of StateMachineStarterFunction lambda
    Value: !GetAtt StateMachineStarterFunction.Arn
    Export:
      Name: StateMachineStarterFunctionArn

  DocumentationFunctionArn:
    Description: ARN of DocumentationFunction lambda
    Value: !GetAtt DocumentationFunction.Arn
    Export:
      Name: DocumentationFunctionArn

  GenerationCompleteFunctionArn:
    Description: ARN of GenerationCompleteFunction lambda
    Value: !GetAtt GenerationCompleteFunction.Arn
    Export:
      Name: GenerationCompleteFunctionArn

  GtmSubDocsCreatorFunctionArn:
    Description: ARN of GtmSubDocsCreatorFunction lambda
    Value: !GetAtt GtmSubDocsCreatorFunction.Arn
    Export:
      Name: GtmSubDocsCreatorFunctionArn

  DownloadAsPDFFunctionArn:
    Description: ARN of DownloadAsPDFFunction lambda
    Value: !GetAtt DownloadAsPDFFunction.Arn
    Export:
      Name: DocumentationFunctionArn
