AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Feedback feature for CAMMI

Resources:
  NewCampaignFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: new-campaign
      Handler: app.lambda_handler
      CodeUri: src/new-campaign/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles users campaigns
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  ExistingCampaignFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: existing-campaign
      Handler: app.lambda_handler
      CodeUri: src/existing-campaign/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles users existing campaigns
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

Outputs:
  NewCampaignFunctionArn:
    Description: ARN of new campaign Lambda
    Value: !GetAtt NewCampaignFunction.Arn
    Export:
      Name: NewCampaignFunctionArn

  ExistingCampaignFunctionArn:
    Description: ARN of existing campaigns Lambda
    Value: !GetAtt ExistingCampaignFunction.Arn
    Export:
      Name: ExistingCampaignFunctionArn