AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Real-Time Text WebSocket Module

Resources:
  RealTimeWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: RealTimeText-WebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${RealTimeWebSocketApi}-access-logs
      RetentionInDays: 14
  
  RealTimeIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RealTimeWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RealtimeTextFrontEndFunctionArn}/invocations
        - RealtimeTextFrontEndFunctionArn: !ImportValue RealtimeTextFrontEndFunctionArn
      CredentialsArn: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
      IntegrationMethod: POST

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RealTimeWebSocketApi
      RouteKey: "$connect"
      Target: !Sub "integrations/${RealTimeIntegration}"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RealTimeWebSocketApi
      RouteKey: "$disconnect"
      Target: !Sub "integrations/${RealTimeIntegration}"

  RealTimeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RealTimeWebSocketApi
      RouteKey: "realtimetext"
      Target: !Sub "integrations/${RealTimeIntegration}"

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - RealTimeRoute
    Properties:
      ApiId: !Ref RealTimeWebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: WebSocketDeployment
    Properties:
      StageName: dev
      ApiId: !Ref RealTimeWebSocketApi
      DeploymentId: !Ref WebSocketDeployment
      AccessLogSettings:
        DestinationArn: !GetAtt WebSocketLogGroup.Arn
        Format: |
          {"requestId":"$context.requestId","requestTime":"$context.requestTime","routeKey":"$context.routeKey","status":"$context.status","connectionId":"$context.connectionId"}
      DefaultRouteSettings:
        DataTraceEnabled: true
        LoggingLevel: INFO
        DetailedMetricsEnabled: true

Outputs:
  RealTimeWebSocketApiId:
    Description: Real-Time WebSocket API ID
    Value: !Ref RealTimeWebSocketApi
    Export:
      Name: RealTime-WebSocketApiId

  RealTimeWebSocketEndpoint:
    Description: Real-Time WebSocket Endpoint
    Value: !Sub "wss://${RealTimeWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Export:
      Name: RealTime-WebSocketEndpoint
