AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth feature for CAMMI - handles Google OAuth login and callback


Resources:
  AuthLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: continue-with-google
      Handler: app.lambda_handler
      CodeUri: src/continue-with-google/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles user login via Google OAuth
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Layers:
        - !ImportValue GoogleLibrariesLayerArn
      Environment:
        Variables:
          CLIENT_ID: "{{resolve:secretsmanager:cammi-google-secrets:SecretString:CLIENT_ID}}"
          CLIENT_SECRET: "{{resolve:secretsmanager:cammi-google-secrets:SecretString:CLIENT_SECRET}}"
          ZOHO_APP_PASSWORD: "{{resolve:secretsmanager:cammi-google-secrets:SecretString:ZOHO_APP_PASSWORD}}"
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: register
      Handler: app.lambda_handler
      CodeUri: src/register/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles user registeration via sign-up
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

Outputs:
  AuthLoginFunctionArn:
    Description: "Arn of Google OAuth Login Function"
    Value: !GetAtt AuthLoginFunction.Arn
  
  RegisterFunctionArn:
    Description: "Arn of user registeration function"
    Value: !GetAtt RegisterFunction.Arn
