AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth feature for CAMMI - handles Google OAuth login and callback

Resources:
  AuthLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: continue-with-google
      Handler: app.lambda_handler
      CodeUri: src/continue-with-google/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles user login via Google OAuth
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Layers:
        - !ImportValue Google1LibrariesLayerArn
      Environment:
        Variables:
          CLIENT_ID: "{{resolve:secretsmanager:cammi-secrets:SecretString:CLIENT_ID}}"
          CLIENT_SECRET: "{{resolve:secretsmanager:cammi-secrets:SecretString:CLIENT_SECRET}}"
          ZOHO_APP_PASSWORD: "{{resolve:secretsmanager:cammi-secrets:SecretString:ZOHO_APP_PASSWORD}}"
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: register
      Handler: app.lambda_handler
      CodeUri: src/register/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles user registration via sign-up
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: forgot-password
      Handler: app.lambda_handler
      CodeUri: src/forgot-password/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles user password reset via forgot-password
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  LoginLogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: login-logout
      Handler: app.lambda_handler
      CodeUri: src/login-logout/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles user session management via sign-in and register
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

Outputs:
  AuthLoginFunctionArn:
    Description: "Arn of Google OAuth Login Function"
    Value: !GetAtt AuthLoginFunction.Arn

  RegisterFunctionArn:
    Description: "Arn of user registration function"
    Value: !GetAtt RegisterFunction.Arn
    Export: 
      Name: RegisterFunctionArn

  ForgotPasswordFunctionArn:
    Description: "Arn of user password management function"
    Value: !GetAtt ForgotPasswordFunction.Arn

  LoginLogoutFunctionArn:
    Description: "Arn of user session management function"
    Value: !GetAtt LoginLogoutFunction.Arn
    Export: 
      Name: LoginLogoutFunctionArn    
