AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB tables for CAMMI - users, feedback, onboarding, projects, posts, etc.

Resources:

  ###################################################
  # Users Table
  ###################################################
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: session_id-index
          KeySchema:
            - AttributeName: session_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ###################################################
  # Users Feedback Table
  ###################################################
  UsersFeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-feedback-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  ###################################################
  # Onboarding Questions Table
  ###################################################
  UserOnboardingQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: onboarding-questions-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: question
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: question
          KeyType: RANGE

  ###################################################
  # Organizations Table
  ###################################################
  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: organizations-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ###################################################
  # Projects Table
  ###################################################
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: projects-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ###################################################
  # Stripe Table
  ###################################################
  StripeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: stripe-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  ###################################################
  # Payment History Table
  ###################################################
  PaymentHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: payment-history-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: index_id
          AttributeType: S
      KeySchema:
        - AttributeName: index_id
          KeyType: HASH

  ###################################################
  # Review Documents Table
  ###################################################
  ReviewDocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: review-documents-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: document_type_uuid
          AttributeType: S
      KeySchema:
        - AttributeName: project_id
          KeyType: HASH
        - AttributeName: document_type_uuid
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ###################################################
  # Documents History Table
  ###################################################
  DocumentsHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: documents-history-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: document_type_uuid
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: document_type_uuid
          KeyType: RANGE

  ###################################################
  # Project Questions Table
  ###################################################
  ProjectQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: project-questions-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: question_id
          AttributeType: S
      KeySchema:
        - AttributeName: project_id
          KeyType: HASH
        - AttributeName: question_id
          KeyType: RANGE

  ###################################################
  # LinkedIn Posts Table
  ###################################################
  LinkedInPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: linkedin-posts-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sub
          AttributeType: S
        - AttributeName: post_time
          AttributeType: S
      KeySchema:
        - AttributeName: sub
          KeyType: HASH
        - AttributeName: post_time
          KeyType: RANGE

  ###################################################
  # Wordpress Posts Table
  ###################################################
  WordpressPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: wordpress-posts-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: post_id
          AttributeType: S
        - AttributeName: publish_at
          AttributeType: S
      KeySchema:
        - AttributeName: post_id
          KeyType: HASH
        - AttributeName: publish_at
          KeyType: RANGE

  ###################################################
  # Wordpress Sites Table
  ###################################################
  WordpressSitesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: wordpress-sites-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sitename
          AttributeType: S
      KeySchema:
        - AttributeName: sitename
          KeyType: HASH

  ###################################################
  # Post Questions Table (FIXED INDENTATION)
  ###################################################
  PostQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: post-questions-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: organization_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: organization_id-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - post_answer

  ###################################################
  # LinkedIn User Table
  ###################################################
  LinkedInUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: linkedin-user-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sub
          AttributeType: S
      KeySchema:
        - AttributeName: sub
          KeyType: HASH

  ###################################################
  # Claude Usage Logs Table
  ###################################################
  ClaudeUsageLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: claude-usage-logs-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: run_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: run_id
          KeyType: RANGE

Outputs:

  UsersTableName:
    Description: Name of the Users table
    Value: !Ref UsersTable
    Export:
      Name: CAMMI-UsersTableName

  UsersFeedbackTableName:
    Description: Name of Users Feedback table
    Value: !Ref UsersFeedbackTable
    Export:
      Name: CAMMI-UsersFeedbackTableName

  UserOnboardingQuestionsTableName:
    Description: Onboarding Questions table
    Value: !Ref UserOnboardingQuestionsTable
    Export:
      Name: CAMMI-UserOnboardingQuestionsTableName

  OrganizationsTableName:
    Description: Organizations table
    Value: !Ref OrganizationsTable
    Export:
      Name: CAMMI-OrganizationsTableName

  ProjectsTableName:
    Description: Projects table
    Value: !Ref ProjectsTable
    Export:
      Name: CAMMI-ProjectsTableName

  StripeTableName:
    Description: Stripe table
    Value: !Ref StripeTable
    Export:
      Name: CAMMI-StripeTableName

  PaymentHistoryTableName:
    Description: Payment History table
    Value: !Ref PaymentHistoryTable
    Export:
      Name: CAMMI-PaymentHistoryTableName

  ReviewDocumentsTableName:
    Description: Review Documents table
    Value: !Ref ReviewDocumentsTable
    Export:
      Name: CAMMI-ReviewDocumentsTableName

  DocumentsHistoryTableName:
    Description: Documents History table
    Value: !Ref DocumentsHistoryTable
    Export:
      Name: CAMMI-DocumentsHistoryTableName

  ProjectQuestionsTableName:
    Description: Project Questions table
    Value: !Ref ProjectQuestionsTable
    Export:
      Name: CAMMI-ProjectQuestionsTableName

  LinkedInPostsTableName:
    Description: LinkedIn Posts table
    Value: !Ref LinkedInPostsTable
    Export:
      Name: CAMMI-LinkedInPostsTableName

  WordpressPostsTableName:
    Description: Wordpress Posts table
    Value: !Ref WordpressPostsTable
    Export:
      Name: CAMMI-WordpressPostsTableName

  WordpressSitesTableName:
    Description: Wordpress Sites table
    Value: !Ref WordpressSitesTable
    Export:
      Name: CAMMI-WordpressSitesTableName

  PostQuestionsTableName:
    Description: Post Questions table
    Value: !Ref PostQuestionsTable
    Export:
      Name: CAMMI-PostQuestionsTableName

  LinkedInUserTableName:
    Description: LinkedIn User table
    Value: !Ref LinkedInUserTable
    Export:
      Name: CAMMI-LinkedInUserTableName

  ClaudeUsageLogsTableName:
    Description: Claude usage logs table
    Value: !Ref ClaudeUsageLogsTable
    Export:
      Name: CAMMI-ClaudeUsageLogsTableName
