AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB tables for CAMMI - users, feedback, and onboarding data storage

Resources:
  ###################################################
  # Users Table
  ###################################################
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  ###################################################
  # Users Feedback Table
  ###################################################
  UsersFeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-feedback-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  ###################################################
  # Onboarding Questions Table
  ###################################################
  UserOnboardingQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: onboarding-questions-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: question
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: question
          KeyType: RANGE

  ###################################################
  # Organizations Table
  ###################################################
  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: organizations-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ###################################################
  # Projects Table
  ###################################################
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: projects-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ###################################################
  # Stripe Table
  ###################################################
  StripeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: stripe-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  ###################################################
  # Payment History Table
  ###################################################
  PaymentHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: payment-history-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: index_id
          AttributeType: S
      KeySchema:
        - AttributeName: index_id
          KeyType: HASH

  ###################################################
  # Review Documents Table
  ###################################################
  ReviewDocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: review-documents-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: document_type_uuid
          AttributeType: S
      KeySchema:
        - AttributeName: project_id
          KeyType: HASH
        - AttributeName: document_type_uuid
          KeyType: RANGE

  ###################################################
  # Documents History Table
  ###################################################

  DocumentsHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: documents-history-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: document_type_uuid
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: document_type_uuid
          KeyType: RANGE

  ###################################################
  # Project Questions Table
  ###################################################

  ProjectQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: project-questions-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: question_id
          AttributeType: S
      KeySchema:
        - AttributeName: project_id
          KeyType: HASH
        - AttributeName: question_id
          KeyType: RANGE

  ###################################################
  # Linkedin Posts Table
  ###################################################

  LinkedInPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: linkedin-posts-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sub
          AttributeType: S
        - AttributeName: post_time
          AttributeType: S
      KeySchema:
        - AttributeName: sub
          KeyType: HASH
        - AttributeName: post_time
          KeyType: RANGE

  ###################################################
  # Wordpress Posts Table
  ###################################################

  WordpressPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: wordpress-posts-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: post_id
          AttributeType: S
        - AttributeName: publish_at
          AttributeType: S
      KeySchema:
        - AttributeName: post_id
          KeyType: HASH
        - AttributeName: publish_at
          KeyType: RANGE

  ###################################################
  # Wordpress Sites Table
  ###################################################

  WordpressSitesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: wordpress-sites-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sitename
          AttributeType: S
      KeySchema:
        - AttributeName: sitename
          KeyType: HASH



Outputs:
  ###################################################
  # Exports for cross-stack references
  ###################################################
  UsersTableName:
    Description: Name of the Users table
    Value: !Ref UsersTable
    Export:
      Name: CAMMI-UsersTableName

  UsersFeedbackTableName:
    Description: Name of the Users Feedback table
    Value: !Ref UsersFeedbackTable
    Export:
      Name: CAMMI-UsersFeedbackTableName

  UserOnboardingQuestionsTableName:
    Description: Name of the Onboarding Questions table
    Value: !Ref UserOnboardingQuestionsTable
    Export:
      Name: CAMMI-UserOnboardingQuestionsTableName

  OrganizationsTableName:
    Description: Name of the Organizations table
    Value: !Ref OrganizationsTable
    Export:
      Name: CAMMI-OrganizationsTableName

  ProjectsTableName:
    Description: Name of the Projects table
    Value: !Ref ProjectsTable
    Export:
      Name: CAMMI-ProjectsTableName

  StripeTableName:
    Description: Name of the Stripe table
    Value: !Ref StripeTable
    Export:
      Name: CAMMI-StripeTableName

  PaymentHistoryTableName:
    Description: Name of the Payment History table
    Value: !Ref PaymentHistoryTable
    Export:
      Name: CAMMI-PaymentHistoryTableName

  ReviewDocumentsTableName:
    Description: Name of the Review Documents table
    Value: !Ref ReviewDocumentsTable
    Export:
      Name: CAMMI-ReviewDocumentsTableName

  DocumentsHistoryTableName:
    Description: Name of the DocumentsHistoryTable
    Value: !Ref DocumentsHistoryTable
    Export:
      Name: CAMMI-DocumentsHistoryTableName

  ProjectQuestionsTableName:
    Description: Name of the ProjectQuestionsTable
    Value: !Ref ProjectQuestionsTable
    Export:
      Name: CAMMI-ProjectQuestionsTableName

  LinkedInPostsTableName:
    Description: Name of the LinkedInPostsTable
    Value: !Ref LinkedInPostsTable
    Export:
      Name: CAMMI-LinkedInPostsTableName

    WordpressPostsTableName:
    Description: Name of the LinkedInPostsTable
    Value: !Ref WordpressPostsTable
    Export:
      Name: CAMMI-WordpressPostsTableName

    WordpressSitesTableName:
    Description: Name of the WordpressSitesTable
    Value: !Ref WordpressSitesTable
    Export:
      Name: CAMMI-WordpressSitesTableName      