AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Google OAuth and common library layer for CAMMI

Resources:
  Google1LibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: google-libraries
      Description: Shared dependencies for Google login, requests, cachecontrol, etc.
      ContentUri: google_layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  GroqLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: groq-libraries
      Description: Shared dependencies for gpt oss etc.
      ContentUri: groq_layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  GeminiLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gemini-libraries
      Description: Shared dependencies for image generation etc.
      ContentUri: gemini_layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  PdfLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pdf-libraries
      Description: Shared dependencies for download as pdf etc.
      ContentUri: pdf_layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  WebLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: web-libraries
      Description: Shared dependencies for web extraction etc.
      ContentUri: web_layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  StripeLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: stripe-libraries
      Description: Shared dependencies for payment gateway feature
      ContentUri: stripe_layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  DocLibrariesLayer1:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: doc-layer-or-not
      Description: Shared dependencies for document generation
      ContentUri: doc-layer-or-not.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete


Outputs:
  Google1LibrariesLayerArn:
    Description: ARN of the Google Libraries Layer
    Value: !Ref Google1LibrariesLayer
    Export:
      Name: Google1LibrariesLayerArn

  GroqLibrariesLayerArn:
    Description: ARN of the Groq Libraries Layer
    Value: !Ref GroqLibrariesLayer
    Export:
      Name: GroqLibrariesLayerArn

  GeminiLibrariesLayerArn:
    Description: ARN of the Gemini Libraries Layer
    Value: !Ref GeminiLibrariesLayer
    Export:
      Name: GeminiLibrariesLayerArn

  PdfLibrariesLayerArn:
    Description: ARN of the PdfPlumber Libraries Layer
    Value: !Ref PdfLibrariesLayer
    Export:
      Name: PdfLibrariesLayerArn

  WebLibrariesLayerArn:
    Description: ARN of the web scrapping Libraries Layer
    Value: !Ref WebLibrariesLayer
    Export:
      Name: WebLibrariesLayerArn

  StripeLibrariesLayerArn:
    Description: ARN of the payment gateway stripe libraries
    Value: !Ref StripeLibrariesLayer
    Export:
      Name: StripeLibrariesLayerArn

  DocLibrariesLayer1Arn:
    Description: ARN of the doc generation or not libraries
    Value: !Ref DocLibrariesLayer1
    Export:
      Name: DocLibrariesLayer1Arn