AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI Blogs

Parameters:
  RootResourceId:
    Type: String
  RestApiId:
    Type: String

Resources:

  # /blogs parent resource
  BlogsParentResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref RootResourceId
      PathPart: blogs
      RestApiId: !Ref RestApiId

  # /blogs/create-blog resource
  CreateBlogFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt BlogsParentResource.ResourceId
      PathPart: create-blog
      RestApiId: !Ref RestApiId

  # POST Method for /blogs/create-blog
  CreateBlogFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref CreateBlogFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateBlogFunctionArn}/invocations
          - CreateBlogFunctionArn: !ImportValue CreateBlogFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  # OPTIONS Method for /blogs/create-blog
  CreateBlogFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref CreateBlogFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /blogs/view-all-blogs resource
  ViewAllBlogsFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt BlogsParentResource.ResourceId
      PathPart: view-all-blogs
      RestApiId: !Ref RestApiId

  # POST Method for /blogs/view-all-blogs
  ViewAllBlogsFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref ViewAllBlogsFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ViewAllBlogsFunctionArn}/invocations
          - ViewAllBlogsFunctionArn: !ImportValue ViewAllBlogsFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  # OPTIONS Method for /blogs/view-all-blogs
  ViewAllBlogsFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref ViewAllBlogsFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /blogs/update-blog resource
  UpdateBlogFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt BlogsParentResource.ResourceId
      PathPart: update-blog
      RestApiId: !Ref RestApiId

  # POST Method for /blogs/update-blog
  UpdateBlogFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref UpdateBlogFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateBlogFunctionArn}/invocations
          - UpdateBlogFunctionArn: !ImportValue UpdateBlogFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  # OPTIONS Method for /blogs/update-blog
  UpdateBlogFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref UpdateBlogFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /blogs/delete-blog resource
  DeleteBlogFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt BlogsParentResource.ResourceId
      PathPart: delete-blog
      RestApiId: !Ref RestApiId

  # POST Method for /blogs/delete-blog
  DeleteBlogFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DeleteBlogFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteBlogFunctionArn}/invocations
          - DeleteBlogFunctionArn: !ImportValue DeleteBlogFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  # OPTIONS Method for /blogs/delete-blog
  DeleteBlogFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DeleteBlogFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
