AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI Admin Portal

Parameters:
  RootResourceId:
    Type: String
  RestApiId:
    Type: String

Resources:
  # /admin-portal
  LinkedInParentResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref RootResourceId
      PathPart: LinkedIn
      RestApiId: !Ref RestApiId

  # /admin-portal/show-balance
  LoginFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt LinkedInParentResource.ResourceId
      PathPart: linkedInLogin
      RestApiId: !Ref RestApiId

  # GET /admin-portal/show-balance
  LoginFunctionResourceGETMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref LoginFunctionResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginFunctionArn}/invocations
          - LoginFunctionArn: !ImportValue LoginFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  # OPTIONS /admin-portal/show-balance
  LoginFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref LoginFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /admin-portal/show-balance
  CallbackFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt LinkedInParentResource.ResourceId
      PathPart: Callback
      RestApiId: !Ref RestApiId

  # GET /admin-portal/show-balance
  CallbackFunctionResourceGETMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref CallbackFunctionResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginFunctionArn}/invocations
          - LoginFunctionArn: !ImportValue LoginFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  # OPTIONS /admin-portal/show-balance
  CallbackFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref CallbackFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Post Resource
  PostFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt LinkedInParentResource.ResourceId
      PathPart: linkedIn-post
      RestApiId: !Ref RestApiId
 
  # POST Method for /feedback/check-customer-feedback
  PostFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref PostFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostFunctionArn}/invocations
          - PostFunctionArn: !ImportValue PostFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000
 
  # OPTIONS Method for /feedback/check-customer-feedback
  PostFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref PostFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Post Resource
  ScheduleFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt LinkedInParentResource.ResourceId
      PathPart: linkedIn-schedule
      RestApiId: !Ref RestApiId
 
  # POST Method for /feedback/check-customer-feedback
  ScheduleFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref ScheduleFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ScheduleFunctionArn}/invocations
          - ScheduleFunctionArn: !ImportValue ScheduleFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000
 
  # OPTIONS Method for /feedback/check-customer-feedback
  ScheduleFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref ScheduleFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true