AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI New Campaign Purpose

Parameters:
  RootResourceId:
    Type: String
  RestApiId:
    Type: String

Resources:
  NewCampaignResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref RootResourceId
      PathPart: new-campaign
      RestApiId: !Ref RestApiId

  LinkParsingFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt NewCampaignResource.ResourceId
      PathPart: link
      RestApiId: !Ref RestApiId

  LinkParsingFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref LinkParsingFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LinkParsingFunctionArn}/invocations
          - LinkParsingFunctionArn: !ImportValue LinkParsingFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  LinkParsingFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref LinkParsingFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  CampaignDocumentFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt NewCampaignResource.ResourceId
      PathPart: document
      RestApiId: !Ref RestApiId

  CampaignDocumentFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref CampaignDocumentFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CampaignDocumentFunctionArn}/invocations
          - CampaignDocumentFunctionArn: !ImportValue CampaignDocumentFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  CampaignDocumentFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref CampaignDocumentFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true 

  QuestionaireFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt NewCampaignResource.ResourceId
      PathPart: questionaire
      RestApiId: !Ref RestApiId

  QuestionaireFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref QuestionaireFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${QuestionaireFunctionArn}/invocations
          - QuestionaireFunctionArn: !ImportValue QuestionaireFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  QuestionaireFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref QuestionaireFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  DocUploadFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt NewCampaignResource.ResourceId
      PathPart: doc-upload
      RestApiId: !Ref RestApiId

  DocUploadFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DocUploadFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DocUploadFunctionArn}/invocations
          - DocUploadFunctionArn: !ImportValue DocUploadFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  DocUploadFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DocUploadFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  RecommendationsFunctionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt NewCampaignResource.ResourceId
      PathPart: recommendations
      RestApiId: !Ref RestApiId

  RecommendationsFunctionResourcePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RecommendationsFunctionResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Credentials: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RecommendationsFunctionArn}/invocations
          - RecommendationsFunctionArn: !ImportValue RecommendationsFunctionArn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        TimeoutInMillis: 29000

  RecommendationsFunctionResourceOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RecommendationsFunctionResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true        