AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI

Resources:

  # --------------------------
  # Main API Gateway REST API Cloud Formation
  # --------------------------
  cammi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cammi-endpoints


  # --------------------------
  # API Deployment
  # --------------------------
  RestAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - Feedback
      - Onboarding
      - Profile
    Properties:
      RestApiId: !Ref cammi


  # --------------------------
  # CloudWatch Log Group
  # --------------------------
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/CammiRestApiLogGroup
      RetentionInDays: 30


  # --------------------------
  # Stage + Logging
  # --------------------------
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref RestAPIDeployment
      RestApiId: !Ref cammi
      StageName: dev
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          DataTraceEnabled: true
          LoggingLevel: INFO
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: '{
            "request_id": "$context.requestId",
            "extended_request_id": "$context.extendedRequestId",
            "source_ip": "$context.identity.sourceIp",
            "caller": "$context.identity.caller",
            "user": "$context.identity.user",
            "request_time": "$context.requestTime",
            "http_method": "$context.httpMethod",
            "resource_path": "$context.resourcePath",
            "protocol": "$context.protocol",
            "status_code": "$context.status",
            "response_length": "$context.responseLength",
            "body": "$input.body",
            "params": "$input.params",
            "context_error_message": "$context.error.message",
            "integration_latency": "$context.integrationLatency",
            "response_latency": "$context.responseLatency"
          }'


  # --------------------------
  # Logging IAM Role
  # --------------------------
  ApiLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows the API to log errors to CloudWatch Logs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"


  # --------------------------
  # Enable CloudWatch Logging for API GW
  # --------------------------
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiLoggingRole.Arn


  # --------------------------
  # Feedback Nested Application
  # --------------------------
  Feedback:
    Type: AWS::Serverless::Application
    Properties:
      Location: feedback.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  Onboarding:
    Type: AWS::Serverless::Application
    Properties:
      Location: onboarding.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  Profile:
    Type: AWS::Serverless::Application
    Properties:
      Location: profile.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi



Outputs:

  CammiApiId:
    Description: Cammi API ID
    Value: !Ref cammi


