AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI

Resources:

  # --------------------------
  # Main API Gateway REST API Cloud Formation
  # --------------------------
  cammi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cammi-endpoints


  # --------------------------
  # API Deployment
  # --------------------------
  RestAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - Feedback
      - Onboarding
      - Profile
      - AIGeneration
      - Auth
      - AdminPortal
      - BrandSetup
      - Dashboard
      - PaymentGateway
      - ProjectOrganization
      - LinkedIn
      - Schedular
      - Calendar
      - WordPress
      - Lambda
      - DocumentGeneration
      - Tour
      - Support
      - WordpressAnalytics
      - QuickPost
      - NewCampaign
      - ExecutionReadyCampaigns
    Properties:
      RestApiId: !Ref cammi


  # --------------------------
  # CloudWatch Log Group
  # --------------------------
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/CammiRestApiLogGroup
      RetentionInDays: 30


  # --------------------------
  # Stage + Logging
  # --------------------------
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref RestAPIDeployment
      RestApiId: !Ref cammi
      StageName: dev
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          DataTraceEnabled: true
          LoggingLevel: INFO
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: '{
            "request_id": "$context.requestId",
            "extended_request_id": "$context.extendedRequestId",
            "source_ip": "$context.identity.sourceIp",
            "caller": "$context.identity.caller",
            "user": "$context.identity.user",
            "request_time": "$context.requestTime",
            "http_method": "$context.httpMethod",
            "resource_path": "$context.resourcePath",
            "protocol": "$context.protocol",
            "status_code": "$context.status",
            "response_length": "$context.responseLength",
            "body": "$input.body",
            "params": "$input.params",
            "context_error_message": "$context.error.message",
            "integration_latency": "$context.integrationLatency",
            "response_latency": "$context.responseLatency"
          }'


  # --------------------------
  # Logging IAM Role
  # --------------------------
  ApiLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows the API to log errors to CloudWatch Logs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"


  # --------------------------
  # Enable CloudWatch Logging for API GW
  # --------------------------
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiLoggingRole.Arn


  # --------------------------
  # Feedback Nested Application
  # --------------------------
  Feedback:
    Type: AWS::Serverless::Application
    Properties:
      Location: feedback.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  Onboarding:
    Type: AWS::Serverless::Application
    Properties:
      Location: onboarding.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  Profile:
    Type: AWS::Serverless::Application
    Properties:
      Location: profile.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  AIGeneration:
    Type: AWS::Serverless::Application
    Properties:
      Location: ai-generation.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  Auth:
    Type: AWS::Serverless::Application
    Properties:
      Location: auth.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi 

  AdminPortal:
    Type: AWS::Serverless::Application
    Properties:
      Location: admin-portal.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  BrandSetup:
    Type: AWS::Serverless::Application
    Properties:
      Location: brand-setup.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi 

  Dashboard:
    Type: AWS::Serverless::Application
    Properties:
      Location: dashboard.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  PaymentGateway:
    Type: AWS::Serverless::Application
    Properties:
      Location: payment-gateway.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi     

  ProjectOrganization:
    Type: AWS::Serverless::Application
    Properties:
      Location: project-organization.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi      

  LinkedIn:
    Type: AWS::Serverless::Application
    Properties:
      Location: linkedIn.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi 

  Schedular:
    Type: AWS::Serverless::Application
    Properties:
      Location: schedular.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  Calendar:
    Type: AWS::Serverless::Application
    Properties:
      Location: calendar.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  WordPress:
    Type: AWS::Serverless::Application
    Properties:
      Location: wordpress.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  Lambda:
    Type: AWS::Serverless::Application
    Properties:
      Location: common.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  DocumentGeneration:
    Type: AWS::Serverless::Application
    Properties:
      Location: document-generation.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  Tour:
    Type: AWS::Serverless::Application
    Properties:
      Location: tour.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi   

  Support:
    Type: AWS::Serverless::Application
    Properties:
      Location: support.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  WordpressAnalytics:
    Type: AWS::Serverless::Application
    Properties:
      Location: wordpress-analytics.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi  

  QuickPost:
    Type: AWS::Serverless::Application
    Properties:
      Location: quick-post.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  NewCampaign:
    Type: AWS::Serverless::Application
    Properties:
      Location: new-campaign.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi

  ExecutionReadyCampaigns:
    Type: AWS::Serverless::Application
    Properties:
      Location: execution-ready-campaigns.yaml
      Parameters:
        RootResourceId: !GetAtt cammi.RootResourceId
        RestApiId: !Ref cammi                                          

Outputs:
  CammiApiId:
    Description: Cammi API ID
    Value: !Ref cammi


