AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Template for CAMMI Websockets with X-Ray Tracing and Access Logging

Resources:
  CAMMIWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: CAMMIWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  UploadTextExtractFunctionWebSocketLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref CAMMIWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadTextExtractFunctionArn}/invocations
        - UploadTextExtractFunctionArn: !ImportValue UploadTextExtractFunctionArn
      CredentialsArn: !ImportValue CAMMI-ApiGatewayFunctionRoleArn
      IntegrationMethod: POST

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref CAMMIWebSocketApi
      RouteKey: "$connect"
      OperationName: ConnectRoute
      Target: !Sub "integrations/${UploadTextExtractFunctionWebSocketLambdaIntegration}"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref CAMMIWebSocketApi
      RouteKey: "$disconnect"
      OperationName: DisconnectRoute
      Target: !Sub "integrations/${UploadTextExtractFunctionWebSocketLambdaIntegration}"

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref CAMMIWebSocketApi
      RouteKey: "$default"
      OperationName: DefaultRoute
      Target: !Sub "integrations/${UploadTextExtractFunctionWebSocketLambdaIntegration}"

  WebSocketLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${CAMMIWebSocketApi}-access-logs
      RetentionInDays: 14

  CAMMIWebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref CAMMIWebSocketApi

  CAMMIWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: CAMMIWebSocketDeployment
    Properties:
      StageName: dev
      Description: dev Stage with tracing enabled
      ApiId: !Ref CAMMIWebSocketApi
      DeploymentId: !Ref CAMMIWebSocketDeployment
      # AccessLogSettings:
      #   DestinationArn: !Sub "${WebSocketLogGroup.Arn}:*"
      #   Format: |
      #     {"requestId":"$context.requestId","requestTime":"$context.requestTime","routeKey":"$context.routeKey","status":"$context.status","connectionId":"$context.connectionId"}
      # DefaultRouteSettings:
      #   DataTraceEnabled: true
      #   LoggingLevel: INFO
      #   MetricsEnabled: true
      # TracingEnabled: true

Outputs:
  CAMMIWebSocketApiId:
    Description: The ID of the CAMMI WebSocket API
    Value: !Ref CAMMIWebSocketApi
    Export:
      Name: CAMMI-WebSocketApiId

  CAMMIWebSocketApiEndpoint:
    Description: The WebSocket API endpoint URL
    Value: !Sub wss://${CAMMIWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev
    Export:
      Name: CAMMI-WebSocketApiEndpoint
