AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Content Generation Feature for CAMMI - handles content generation part of Scheduler

Resources:
  ###################################################
  # Image Generation Lambda
  ###################################################
  ImageGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: image-generation
      Handler: app.lambda_handler
      CodeUri: src/image-generation/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 10240
      Description: Handles Image Generation Lambda
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue GeminiLibrariesLayerArn
      Environment:
        Variables:
          PROJECT_ID: "{{resolve:secretsmanager:cammi-secrets:SecretString:project_id}}"
          PRIVATE_KEY_ID: "{{resolve:secretsmanager:cammi-secrets:SecretString:private_key_id}}"
          PRIVATE_KEY: "{{resolve:secretsmanager:cammi-secrets:SecretString:private_key}}"
          CLIENT_EMAIL: "{{resolve:secretsmanager:cammi-secrets:SecretString:client_email}}"
          CLIENT_ID: "{{resolve:secretsmanager:cammi-secrets:SecretString:client_id}}"
          AUTH_PROVIDER_X509_CERT_URL: "{{resolve:secretsmanager:cammi-secrets:SecretString:auth_provider_x509_cert_url}}"
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  ###################################################
  # Text Generation Lambda
  ###################################################
  TextGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: text-generation
      Handler: app.lambda_handler
      CodeUri: src/text-generation/
      Runtime: python3.13
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      Description: Handles AI Text Post Generator Lambda
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue GroqLibrariesLayerArn
      Environment:
        Variables:
          GROQ_API_KEY: "{{resolve:secretsmanager:cammi-secrets:SecretString:GROQ_API_KEY}}"
          POST_QUESTIONS_TABLE: !ImportValue CAMMI-PostQuestionsTableName

Outputs:
  ImageGenerationFunctionArn:
    Description: ARN of ImageGenerationFunction Lambda
    Value: !GetAtt ImageGenerationFunction.Arn
    Export:
      Name: ImageGenerationFunctionArn

  TextGenerationFunctionArn:
    Description: ARN of TextGenerationFunction Lambda
    Value: !GetAtt TextGenerationFunction.Arn
    Export:
      Name: TextGenerationFunctionArn
