AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Support feature for CAMMI

Resources:

  WordpressAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: wordpress-analytics
      Handler: app.lambda_handler
      CodeUri: src/wordpress-analytics/
      Runtime: python3.12
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles wordpress analytics.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue G4TagLayerArn
        # - !ImportValue AnalyticsLayerArn
        # - !ImportValue GoogleLayer3Arn  
        # - !ImportValue GoogleLayer2Arn 
        - !ImportValue LatestG4TagLayerArn     
      Environment:
        Variables:
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName
          ANALYTICS_TABLE: !ImportValue CAMMI-AnalyticsTableName 

  WordpressDimensionsAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: wordpress-dimension-analytics
      Handler: app.lambda_handler
      CodeUri: src/wordpress-dimensions-analytics/
      Runtime: python3.12
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles wordpress Dimensions analytics.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue G4TagLayerArn
        # - !ImportValue AnalyticsLayerArn
        # - !ImportValue GoogleLayer3Arn  
        # - !ImportValue GoogleLayer2Arn  
        - !ImportValue LatestG4TagLayerArn              
      Environment:
        Variables:
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName
          ANALYTICS_TABLE: !ImportValue CAMMI-AnalyticsTableName 

  StatusUpdateAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-status-analytics
      Handler: app.lambda_handler
      CodeUri: src/status-update-analytics/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles support ticket exists or not against user.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          EMAIL_SUPPORT_TABLE: !ImportValue CAMMI-EmailSupportTableName 
          TICKET_COUNTER_TABLE: !ImportValue CAMMI-ETicketCounterTableName           


Outputs:
  WordpressAnalyticsFunctionArn:
    Description: ARN of user onboarding Lambda
    Value: !GetAtt WordpressAnalyticsFunction.Arn
    Export:
      Name: WordpressAnalyticsFunctionArn  

  WordpressDimensionsAnalyticsFunctionArn:
    Description: ARN of user onboarding Lambda
    Value: !GetAtt WordpressDimensionsAnalyticsFunction.Arn
    Export:
      Name: WordpressDimensionsAnalyticsFunctionArn    

  StatusUpdateAnalyticsFunctionArn:
    Description: ARN of user onboarding Lambda
    Value: !GetAtt StatusUpdateAnalyticsFunction.Arn
    Export:
      Name: StatusUpdateAnalyticsFunctionArn          