AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Brand Setup feature for CAMMI

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name imported from parent stack

Resources:
  WebScrappingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: web-scraping
      Handler: app.lambda_handler
      CodeUri: src/web-scrapping/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles web scrapping for brand setup
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue WebLibrariesLayerArn
      Environment:
        Variables:
          HYPERBROWSER_API_KEY: "{{resolve:secretsmanager:cammi-secrets:SecretString:HYPERBROWSER_API_KEY}}"
          S3_BUCKET_NAME: !Ref S3BucketName

  PdfExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pdf-extraction
      Handler: app.lambda_handler
      CodeUri: src/pdf-extraction/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles PDF extraction for brand setup
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue PdfLibrariesLayerArn

  PdfExtractionEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PdfExtractionEventRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PdfExtractionEventPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  PdfExtractionEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: PdfExtractionEventRule
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref S3BucketName
          object:
            key:
              - wildcard: 'pdf_files/'
      Targets:
        - Id: "PdfExtractionTrigger"
          RoleArn: !GetAtt PdfExtractionEventRole.Arn
          Arn: !GetAtt PdfExtractionFunction.Arn

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload
      Handler: app.lambda_handler
      CodeUri: src/upload/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 512
      Tracing: Active
      Description: Handles PDF upload and processing with fact extraction
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue PdfLibrariesLayerArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  AnswerFactExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: answer-fact-extraction
      Handler: app.lambda_handler
      CodeUri: src/answer-fact-extraction/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles frontend_to_s3
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName          



Outputs:
  WebScrappingFunctionArn:
    Description: ARN of web scrapping Lambda
    Value: !GetAtt WebScrappingFunction.Arn
    Export:
      Name: WebScrappingFunctionArn    
    
  PdfExtractionFunctionArn:
    Description: ARN of PDF extraction Lambda
    Value: !GetAtt PdfExtractionFunction.Arn

  UploadFunctionArn:
    Description: ARN of pdf upload lambda
    Value: !GetAtt UploadFunction.Arn
    Export:
      Name: UploadFunctionArn

  AnswerFactExtractionFunctionArn:
    Description: ARN of pdf AnswerFactExtraction lambda
    Value: !GetAtt AnswerFactExtractionFunction.Arn
    Export:
      Name: AnswerFactExtractionFunctionArn      
      