version = 0.1

[default.global.parameters]
stack_name = "CAMMI"
region = "us-east-1"

[default.build.parameters]
use_container = false
parallel = true
cached = true

[default.deploy.parameters]
s3_bucket = "cammi"
s3_prefix = "cammi"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
image_repositories = [] 