AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application replicated from AWS Console resources.
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

# ============================================================
# GLOBAL SETTINGS
# ============================================================
Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: Active

# ============================================================
# RESOURCES
# ============================================================
Resources:

  # ---------------------------------------------------
  # Shared API Gateway for CAMMI
  # ---------------------------------------------------
  # CammiApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     Name: CammiApi
  #     StageName: cammi-mvp
  #     TracingEnabled: true
  #     EndpointConfiguration: REGIONAL

  # ---------------------------------------------------
  # DynamoDB stack (new nested application)
  # ---------------------------------------------------
  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  GoogleLibrariesLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: layers/template.yaml
  # ---------------------------------------------------
  # Feature-based Modules (examples)
  # ---------------------------------------------------
  # AuthFeature:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: auth/template.yaml
  #     Parameters:
  #       ParentApiId: !Ref CammiApi
  #       StageName: cammi-mvp
  
  FeedbackFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: feedback/template.yaml
      # Parameters:
      #   ParentApiId: !Ref CammiApi
      #   StageName: cammi-mvp

# ============================================================
# OUTPUTS
# ============================================================
# Outputs:
#   ApiUrl:
#     Description: "Base URL for CAMMI API Gateway"
#     Value: !Sub "https://${CammiApi}.execute-api.${AWS::Region}.amazonaws.com/cammi-mvp"
#     Export:
#       Name: CAMMI-Dev-ApiUrl
