AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application replicated from AWS Console resources.
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

# ============================================================
# GLOBAL SETTINGS
# ============================================================
Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 512
    Architectures:
      - x86_64
    Tracing: Active

# ============================================================
# RESOURCES
# ============================================================
Resources:

  # ---------------------------------------------------
  # Shared API Gateway for CAMMI
  # ---------------------------------------------------
  CammiApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CammiApi
      StageName: cammi-mvp
      TracingEnabled: true
      EndpointConfiguration: REGIONAL

  # ---------------------------------------------------
  # Feature-based Modules (examples)
  # ---------------------------------------------------
  AuthFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: features/auth/template.yaml

  DataFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: features/data/template.yaml

  NotificationsFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: features/notifications/template.yaml

# ============================================================
# OUTPUTS
# ============================================================
Outputs:
  ApiUrl:
    Description: "Base URL for CAMMI API Gateway"
    Value: !Sub "https://${CammiApi}.execute-api.${AWS::Region}.amazonaws.com/cammi-mvp/"
