AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application replicated from AWS Console resources.
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

# ============================================================
# GLOBAL SETTINGS
# ============================================================
Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: Active

# ============================================================
# RESOURCES
# ============================================================
Resources:

  # ---------------------------------------------------
  # DynamoDB stack (nested application)
  # ---------------------------------------------------
  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  # ---------------------------------------------------
  # Google Libraries Layer stack
  # ---------------------------------------------------
  GoogleLibrariesLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: layers/template.yaml

  # ---------------------------------------------------
  # Feature-based Modules (example)
  # ---------------------------------------------------
  # AuthFeature:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: auth/template.yaml

  FeedbackFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: feedback/template.yaml

# ============================================================
# OUTPUTS
# ============================================================
Outputs:
  DynamoDBStackOutput:
    Description: "Outputs from nested DynamoDB stack"
    Value: !Ref DynamoDBStack

  GoogleLibrariesLayerStackOutput:
    Description: "Outputs from Google libraries layer stack"
    Value: !Ref GoogleLibrariesLayerStack

  FeedbackFeatureOutput:
    Description: "Outputs from Feedback feature stack"
    Value: !Ref FeedbackFeature
