AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application orchestrator
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: Active

Resources:

  # Nested DynamoDB stack
  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  # Nested Google Libraries Layer stack
  GoogleLibrariesLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: layers/template.yaml

  # Feedback Lambdas
  FeedbackFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: feedback/template.yaml
      Parameters:
        StageName: cammi-mvp

Outputs:
  DynamoDBStackOutput:
    Description: Outputs from nested DynamoDB stack
    Value: !Ref DynamoDBStack

  GoogleLibrariesLayerStackOutput:
    Description: Outputs from Google libraries layer stack
    Value: !Ref GoogleLibrariesLayerStack

  FeedbackFeatureOutput:
    Description: Outputs from Feedback feature stack
    Value: !Ref FeedbackFeature