AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application orchestrator
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  LayersStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: layers/template.yaml

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/template.yaml

  FeedbackFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: feedback/template.yaml
  
  AuthFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - LayersStack
    Properties:
      Location: auth/template.yaml
  
  OnboardingFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: onboarding/template.yaml
  
  ProjectOrganizationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: project-organization/template.yaml

  ApiGatewayFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - FeedbackFeature
    Properties:
      Location: API/template.yaml

  BrandSetupFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - S3Stack
    Properties:
      Location: brand-setup/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  AdminPortalFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: admin-portal/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  LambdaFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: lambda/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  DashboardFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: dashboard/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  DocumentGenerationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: document-generation/template.yaml
      Parameters:                            
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  PaymentGatewayFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: payment-gateway/template.yaml 

  AIGenerationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - LayersStack
    Properties:
      Location: ai-generation/template.yaml

  CalendarFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: calendar/template.yaml
      Parameters:                            
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName


  WordpressFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack      
    Properties:
      Location: wordpress/template.yaml
      Parameters:                            
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  SchedulerFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: scheduler/template.yaml

  LinkedInFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: linkedIn/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName



Outputs:
  LayersStackOutput:
    Description: Outputs from nested layers stack
    Value: !Ref LayersStack

  DynamoDBStackOutput:
    Description: Outputs from nested DynamoDB stack
    Value: !Ref DynamoDBStack

  S3StackOutput:
    Description: Outputs from Cammi S3 stack
    Value: !Ref S3Stack

  FeedbackFeatureOutput:
    Description: Outputs from Feedback feature stack
    Value: !Ref FeedbackFeature

  AuthFeatureOutput:
    Description: Outputs from Auth feature stack
    Value: !Ref AuthFeature

  OnboardingFeatureOutput:
    Description: Outputs from Onboarding feature stack
    Value: !Ref OnboardingFeature
  
  ProjectOrganizationFeatureOutput:
    Description: Outputs from Project Organization feature stack
    Value: !Ref ProjectOrganizationFeature

  ApiGatewayFeatureOutput:
    Description: Outputs from API Gateway feature stack
    Value: !Ref ApiGatewayFeature

  AdminPortalFeatureOutput:
    Description: Outputs from Admin Portal feature stack
    Value: !Ref AdminPortalFeature

  PaymentGatewayFeatureOutput:
    Description: Outputs from Payment Gateway feature stack
    Value: !Ref PaymentGatewayFeature

  LambdaFeatureOutput:
    Description: Outputs from LambdaFeature feature stack
    Value: !Ref LambdaFeature

  DashboardFeatureOutput:
    Description: Outputs from DashboardFeature feature stack
    Value: !Ref DashboardFeature

  DocumentGenerationFeatureOutput:
    Description: Outputs from DocumentGenerationFeature feature stack
    Value: !Ref DocumentGenerationFeature

  AIGenerationFeatureOutput:
    Description: Outputs from AIGenerationFeature stack
    Value: !Ref AIGenerationFeature

  CalendarFeatureOutput:
    Description: Outputs from CalendarFeature stack
    Value: !Ref CalendarFeature

  WordpressFeatureOuput:
    Description: Outputs from WordpressFeature stack
    Value: !Ref WordpressFeature

  SchedulerFeatureOutput:
    Description: Outputs from SchedulerFeature stack
    Value: !Ref SchedulerFeature

  LinkedInFeatureOutput:
    Description: Outputs from LinkedInFeature stack
    Value: !Ref LinkedInFeature   