AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application orchestrator
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  LayersStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: layers/template.yaml

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/template.yaml

  FeedbackFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: feedback/template.yaml
  
  AuthFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - LayersStack
    Properties:
      Location: auth/template.yaml
  
  OnboardingFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: onboarding/template.yaml
  
  ProjectOrganizationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: project-organization/template.yaml

  ApiGatewayFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - FeedbackFeature
    Properties:
      Location: API/template.yaml

  BrandSetupFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - S3Stack
    Properties:
      Location: brand-setup/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  AdminPortalFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: admin-portal/template.yaml
  
  PaymentGatewayFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: payment-gateway/template.yaml

Outputs:
  LayersStackOutput:
    Description: Outputs from nested layers stack
    Value: !Ref LayersStack

  DynamoDBStackOutput:
    Description: Outputs from nested DynamoDB stack
    Value: !Ref DynamoDBStack

  S3StackOutput:
    Description: Outputs from Cammi S3 stack
    Value: !Ref S3Stack

  FeedbackFeatureOutput:
    Description: Outputs from Feedback feature stack
    Value: !Ref FeedbackFeature

  AuthFeatureOutput:
    Description: Outputs from Auth feature stack
    Value: !Ref AuthFeature

  OnboardingFeatureOutput:
    Description: Outputs from Onboarding feature stack
    Value: !Ref OnboardingFeature
  
  ProjectOrganizationFeatureOutput:
    Description: Outputs from Project Organization feature stack
    Value: !Ref ProjectOrganizationFeature

  AdminPortalFeatureOutput:
    Description: Outputs from Admin Portal feature stack
    Value: !Ref AdminPortalFeature

  PaymentGatewayFeatureOutput:
    Description: Outputs from Payment Gateway feature stack
    Value: !Ref PaymentGatewayFeature
