AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CAMMI - Serverless Application orchestrator
  Python 3.13 runtime, 15-minute Lambda timeout, feature-based structure.

Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  IAMStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: IAM/template.yaml

  LayersStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: layers/template.yaml

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/template.yaml

  FeedbackFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: feedback/template.yaml

  AuthFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - LayersStack
    Properties:
      Location: auth/template.yaml

  OnboardingFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: onboarding/template.yaml

  ProjectOrganizationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: project-organization/template.yaml

  ApiGatewayFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - FeedbackFeature
      - OnboardingFeature
      - ProfileFeature
      - AIGenerationFeature
      - AuthFeature
      - AdminPortalFeature
      - BrandSetupFeature
      - DashboardFeature
      - PaymentGatewayFeature
      - ProjectOrganizationFeature
      - LinkedInFeature
      - SchedulerFeature
      - CalendarFeature
      - WordpressFeature
      - LambdaFeature
      - DocumentGenerationFeature
      - TourFeature
      - EmailSupportFeature
      - QuickPostFeature
      - NewCampaignFeature
    Properties:
      Location: API/template.yaml

  BrandSetupFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - S3Stack
    Properties:
      Location: brand-setup/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  AdminPortalFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: admin-portal/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  LambdaFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
      - IAMStack
    Properties:
      Location: lambda/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  DashboardFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: dashboard/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  DocumentGenerationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: document-generation/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  PaymentGatewayFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: payment-gateway/template.yaml

  AIGenerationFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - LayersStack
    Properties:
      Location: ai-generation/template.yaml

  CalendarFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: calendar/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  WordpressFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: wordpress/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  SchedulerFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: scheduler/template.yaml

  LinkedInFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: linkedIn/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  UnifiedStateMachineFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
      - S3Stack
    Properties:
      Location: unified-state-machine/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  EditStateMachineFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - S3Stack
    Properties:
      Location: edit-unified-state-machine/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName

  ProfileFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: profile/template.yaml

  WebSocketFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DocumentGenerationFeature
    Properties:
      Location: websocket/template.yaml

  RealTimeWebSocketFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - LambdaFeature
    Properties:
      Location: real-time-websocket/template.yaml

  UploadWebSocketFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DocumentGenerationFeature
    Properties:
      Location: upload-document-websocket/template.yaml

  StateMachinesFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/template.yaml

  AmplifyStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: amplify/template.yaml

  TourFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - DynamoDBStack
    Properties:
      Location: tour/template.yaml
      
  EmailSupportFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: support/template.yaml   

  AnalyticsFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: analytics/template.yaml

  QuickPostFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - DynamoDBStack
    Properties:
      Location: quick-post/template.yaml

  NewCampaignFeature:
    Type: AWS::Serverless::Application
    DependsOn:
      - IAMStack
      - S3Stack
      - LayersStack
    Properties:
      Location: new-campaign/template.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.CammiBucketName            

Outputs:
  IAMStackOutput:
    Description: Outputs from IAM stack
    Value: !Ref IAMStack

  LayersStackOutput:
    Description: Outputs from layers stack
    Value: !Ref LayersStack

  DynamoDBStackOutput:
    Description: Outputs from DynamoDB stack
    Value: !Ref DynamoDBStack

  S3StackOutput:
    Description: Outputs from S3 stack
    Value: !Ref S3Stack

  FeedbackFeatureOutput:
    Description: Outputs from Feedback feature
    Value: !Ref FeedbackFeature

  AuthFeatureOutput:
    Description: Outputs from Auth feature
    Value: !Ref AuthFeature

  OnboardingFeatureOutput:
    Description: Outputs from Onboarding feature
    Value: !Ref OnboardingFeature

  ProjectOrganizationFeatureOutput:
    Description: Outputs from Project Organization feature
    Value: !Ref ProjectOrganizationFeature

  ApiGatewayFeatureOutput:
    Description: Outputs from API Gateway feature
    Value: !Ref ApiGatewayFeature

  AdminPortalFeatureOutput:
    Description: Outputs from Admin Portal feature
    Value: !Ref AdminPortalFeature

  PaymentGatewayFeatureOutput:
    Description: Outputs from Payment Gateway feature
    Value: !Ref PaymentGatewayFeature

  LambdaFeatureOutput:
    Description: Outputs from Lambda feature
    Value: !Ref LambdaFeature

  DashboardFeatureOutput:
    Description: Outputs from Dashboard feature
    Value: !Ref DashboardFeature

  DocumentGenerationFeatureOutput:
    Description: Outputs from Document Generation feature
    Value: !Ref DocumentGenerationFeature

  AIGenerationFeatureOutput:
    Description: Outputs from AI Generation feature
    Value: !Ref AIGenerationFeature

  CalendarFeatureOutput:
    Description: Outputs from Calendar feature
    Value: !Ref CalendarFeature

  WordpressFeatureOutput:
    Description: Outputs from Wordpress feature
    Value: !Ref WordpressFeature

  SchedulerFeatureOutput:
    Description: Outputs from Scheduler feature
    Value: !Ref SchedulerFeature

  LinkedInFeatureOutput:
    Description: Outputs from LinkedIn feature
    Value: !Ref LinkedInFeature

  UnifiedStateMachineOutput:
    Description: Outputs from Unified State Machine feature
    Value: !Ref UnifiedStateMachineFeature

  EditStateMachineFeatureOutput:
    Description: Outputs from Edit Unified State Machine feature
    Value: !Ref EditStateMachineFeature

  ProfileFeatureOutput:
    Description: Outputs from profile feature
    Value: !Ref ProfileFeature

  WebSocketFeatureOutput:
    Description: Outputs from websocket feature
    Value: !Ref WebSocketFeature

  RealTimeWebSocketFeatureOutput:
    Description: Outputs from Real time websocket feature
    Value: !Ref RealTimeWebSocketFeature

  UploadWebSocketFeatureOutput:
    Description: Outputs from upload document websocket feature
    Value: !Ref UploadWebSocketFeature

  StateMachinesFeatureOutput:
    Description: Outputs from state machine functions
    Value: !Ref StateMachinesFeature

  AmplifyStackOutput:
    Description: Outputs from the amplify stack
    Value: !Ref AmplifyStack

  TourFeatureOutput:
    Description: Outputs from the tour feature
    Value: !Ref TourFeature

  EmailSupportFeatureOutput:
    Description: Outputs from the tour feature
    Value: !Ref EmailSupportFeature

  AnalyticsFeatureOutput:
    Description: Outputs from the analytics feature
    Value: !Ref AnalyticsFeature

  QuickPostFeatureOutput:
    Description: Outputs from the Quick Post feature
    Value: !Ref QuickPostFeature

  NewCampaignFeatureOutput:
    Description: Outputs from the New campaign feature
    Value: !Ref NewCampaignFeature