AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Document Generation feature for CAMMI

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name imported from parent stack

Resources:

  ###################################################
  # Get Unanswered Questions Data
  ###################################################
  GetUnansweredQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-unanswered-questions
      Handler: app.lambda_handler
      CodeUri: src/get-unanswered-questions/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Returns all questions against a document that are not answered.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName        

  ###################################################
  # User Input Enhancement
  ###################################################
  UserInputEnhancementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user-input-enhancement
      Handler: app.lambda_handler
      CodeUri: src/user-input-enhancement/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: This lambda enhances the user input.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue GroqLibrariesLayerArn
      

  ###################################################
  # Add Questions in DB
  ###################################################
  AddQuestionsInDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: add-questions-in-db
      Handler: app.lambda_handler
      CodeUri: src/add-questions-in-db/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Stores all the answered questions in DB.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName
       
  ###################################################
  # Get Questions Against Document Type
  ###################################################
  GetQuestionsAgainstDocTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-question-against-doc-type
      Handler: app.lambda_handler
      CodeUri: src/get-question-against-doc-type/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Returns questions against Document type to front end.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName            

  ###################################################
  # Edit Question Answer Lambda
  ###################################################
  EditQuestionAnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: edit-question-answer
      Handler: app.lambda_handler
      CodeUri: src/edit-question-answer/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Edits answer of a question and saves it in DB.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName  
            

  ###################################################
  # Answers File Upload to S3 Lambda
  ###################################################
  AnswersFileUploadToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: answers-file-upload-to-s3
      Handler: app.lambda_handler
      CodeUri: src/answers-file-upload-to-s3/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: This lambda uploads answers to S3 as a text file.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          S3_BUCKET_NAME: !Ref S3BucketName   
         

  ###################################################
  # S3 Lambda Trigger
  ###################################################
  S3LambdaTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-lambda-trigger
      Handler: app.lambda_handler
      CodeUri: src/s3-lambda-trigger/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: This lambda triggers a state machine.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          S3_BUCKET_NAME: !Ref S3BucketName

  S3LambdaTriggerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: S3LambdaTriggerFunction
    Properties:
      RetentionInDays: 180
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref S3LambdaTriggerFunction]]
  
  S3EventRuleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3EventRuleRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3EventRulePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  S3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: S3EventRule
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref S3BucketName
          object:
            key:
              - wildcard: '*/*/prompt/businessidea/businessidea/businessidea.txt'
      Targets:
        - Id: "S3LambdaTriggerEvent"
          RoleArn: !GetAtt S3EventRuleRole.Arn
          Arn: !GetAtt  S3LambdaTriggerFunction.Arn

  ###################################################
  # Edit heading Function
  ###################################################

  EditHeadingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: edit-heading
      Handler: app.lambda_handler
      CodeUri: src/edit-heading/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles edit heading function
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          STATE_MACHINE_ARN: "{{resolve:secretsmanager:cammi-secrets:SecretString:STATE_MACHINE_ARN}}"        

  ###################################################
  # Upload Text Extract Function
  ###################################################

  UploadTextExtractFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload-text-extract
      Handler: app.lambda_handler
      CodeUri: src/upload-text-extract/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: WebSocket handler for document text processing. Connects clients, processes uploaded documents through Bedrock AI, extracts Q&A data, saves to ProjectQuestions table, and streams results via WebSocket.
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName  
                                       

###################################################
# Outputs
###################################################
Outputs:
  GetUnansweredQuestionsFunctionArn:
    Description: ARN of GetUnansweredQuestionsFunction Lambda
    Value: !GetAtt GetUnansweredQuestionsFunction.Arn
    Export:
      Name: GetUnansweredQuestionsFunctionArn

  UserInputEnhancementFunctionArn:
    Description: ARN of UserInputEnhancementFunction Lambda
    Value: !GetAtt UserInputEnhancementFunction.Arn
    Export:
      Name: UserInputEnhancementFunctionArn

  AddQuestionsInDBFunctionArn:
    Description: ARN of AddQuestionsInDBFunction Lambda
    Value: !GetAtt AddQuestionsInDBFunction.Arn
    Export:
      Name: AddQuestionsInDBFunctionArn

  GetQuestionsAgainstDocTypeFunctionArn:
    Description: ARN of GetQuestionsAgainstDocTypeFunction Lambda
    Value: !GetAtt GetQuestionsAgainstDocTypeFunction.Arn
    Export:
      Name: GetQuestionsAgainstDocTypeFunctionArn    

  EditQuestionAnswerFunctionArn:
    Description: ARN of EditQuestionAnswerFunction Lambda
    Value: !GetAtt EditQuestionAnswerFunction.Arn    
    Export:
      Name: EditQuestionAnswerFunctionArn      

  AnswersFileUploadToS3FunctionArn:
    Description: ARN of AnswersFileUploadToS3Function Lambda
    Value: !GetAtt AnswersFileUploadToS3Function.Arn
    Export:
      Name: AnswersFileUploadToS3FunctionArn  

  EditHeadingFunctionArn:
    Description: ARN of EditHeadingFunction Lambda
    Value: !GetAtt EditHeadingFunction.Arn
    Export:
      Name: EditHeadingFunctionArn

  UploadTextExtractFunctionArn:
    Description: ARN of UploadTextExtractFunction Lambda
    Value: !GetAtt UploadTextExtractFunction.Arn
    Export:
      Name: UploadTextExtractFunctionArn      
