AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Document Generation feature for CAMMI

Resources:
  ###################################################
  # Get Unanswered Questions Data
  ###################################################
  GetUnansweredQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-unanswered-questions
      Handler: app.lambda_handler
      CodeUri: src/get-unanswered-questions/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Returns all questions against a document that are not answered.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName

  ###################################################
  # User Input Enhancement
  ###################################################
  UserInputEnhancementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user-input-enhancement
      Handler: app.lambda_handler
      CodeUri: src/user-input-enhancement/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: This lambda enhances the user input.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Layers:
        - !ImportValue GroqLibrariesLayerArn

  ###################################################
  # Add Questions in DB
  ###################################################
  AddQuestionsInDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: add-questions-in-db
      Handler: app.lambda_handler
      CodeUri: src/add-questions-in-db/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Stores all the answered questions in DB.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          PROJECT_QUESTIONS_TABLE: !ImportValue CAMMI-ProjectQuestionsTableName

###################################################
# Outputs
###################################################
Outputs:
  GetUnansweredQuestionsFunctionArn:
    Description: ARN of GetUnansweredQuestionsFunction Lambda
    Value: !GetAtt GetUnansweredQuestionsFunction.Arn

  UserInputEnhancementFunctionArn:
    Description: ARN of UserInputEnhancementFunction Lambda
    Value: !GetAtt UserInputEnhancementFunction.Arn

  AddQuestionsInDBFunctionArn:
    Description: ARN of AddQuestionsInDBFunction Lambda
    Value: !GetAtt AddQuestionsInDBFunction.Arn
