AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Unified State Machine Lambdas for document generation for CAMMI

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name imported from parent stack

Resources:
  ###################################################
  # Client ID Registration Lambda
  ###################################################
  ClientIDRegisterationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: client-id-registeration
      Handler: app.lambda_handler
      CodeUri: src/client-id-registeration/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Copies execution_plan.json from flow/{document_type}/ to flow/{user_id}/{document_type}/ in S3 when a new user/document session starts.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  ###################################################
  # Get Next Pending Tier
  ###################################################
  GetNextPendingTierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-next-pending-tier
      Handler: app.lambda_handler
      CodeUri: src/get-next-pending-tier/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Reads execution_plan.json from S3, finds first tier with status=false.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  ###################################################
  # Event Creator
  ###################################################
  EventCreatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event-creator
      Handler: app.lambda_handler
      CodeUri: src/event-creator/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Parses Step Function event input and prepares WebSocket event.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  ###################################################
  # Realtime Text Front End
  ###################################################
  RealtimeTextFrontEndFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: realtime-text-frontend
      Handler: app.lambda_handler
      CodeUri: src/realtime-text-frontend/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Unified WebSocket handler for connect/disconnect/sendMessage.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

  ###################################################
  # Creative Event Lambda
  ###################################################
  CreatorEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: creator-event
      Handler: app.lambda_handler
      CodeUri: src/creator-event/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: JSON body extractor for step states.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role

  ###################################################
  # Update Tier Status Function
  ###################################################
  UpdateTierStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-tier-status
      Handler: app.lambda_handler
      CodeUri: src/update-tier-status/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Updates tier status in execution_plan.json.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  ###################################################
  # Progress Bar Function
  ###################################################
  ProgressBarFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: progress-bar
      Handler: app.lambda_handler
      CodeUri: src/progress-bar/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Calculates and broadcasts document generation progress.
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

###################################################
# Outputs - fixed export names (unique)
###################################################
Outputs:
  ClientIDRegisterationFunctionArn:
    Description: ARN
    Value: !GetAtt ClientIDRegisterationFunction.Arn
    Export:
      Name: ClientIDRegisterationFunctionArn

  GetNextPendingTierFunctionArn:
    Description: ARN
    Value: !GetAtt GetNextPendingTierFunction.Arn
    Export:
      Name: GetNextPendingTierFunctionArn

  EventCreatorFunctionArn:
    Description: ARN
    Value: !GetAtt EventCreatorFunction.Arn
    Export:
      Name: EventCreatorFunctionArn

  RealtimeTextFrontEndFunctionArn:
    Description: ARN
    Value: !GetAtt RealtimeTextFrontEndFunction.Arn
    Export:
      Name: RealtimeTextFrontEndFunctionArn

  CreatorEventFunctionArn:
    Description: ARN
    Value: !GetAtt CreatorEventFunction.Arn
    Export:
      Name: CreatorEventFunctionArn

  UpdateTierStatusFunctionArn:
    Description: ARN
    Value: !GetAtt UpdateTierStatusFunction.Arn
    Export:
      Name: UpdateTierStatusFunctionArn

  ProgressBarFunctionArn:
    Description: ARN
    Value: !GetAtt ProgressBarFunction.Arn
    Export:
      Name: ProgressBarFunctionArn
