AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Onboarding journey of user feature for CAMMI

Resources:
  OnboardingTourFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: onboarding-tour
      Handler: app.lambda_handler
      CodeUri: src/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles user onboarding journey after sign-up
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName

Outputs:
  OnboardingTourFunctionArn:
    Description: ARN of user onboarding journey Lambda
    Value: !GetAtt OnboardingTourFunction.Arn
    Export:
      Name: OnboardingTourFunctionArn