AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: New Campaign Creation feature for CAMMI

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name imported from parent stack

Resources:
  LinkParsingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: link
      Handler: app.lambda_handler
      CodeUri: src/link/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 10240
      Tracing: Active
      Description: Handles link scrapping for new campaign creation
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue WebLibrariesLayerArn
      Environment:
        Variables:
          HYPERBROWSER_API_KEY: "{{resolve:secretsmanager:cammi-secrets:SecretString:HYPERBROWSER_API_KEY}}"
          S3_BUCKET_NAME: !Ref S3BucketName

  CampaignDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: document
      Handler: app.lambda_handler
      CodeUri: src/document/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles frontend file to s3
      Role: !ImportValue CAMMI-LambdaRoleArn
      Layers:
        - !ImportValue PdfLibrariesLayerArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  S3EventRuleRoleNew2:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3EventRuleRoleNew2
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3EventRulePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  S3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: S3EventRuleNew2
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref S3BucketName
          object:
            key:
              - wildcard: 'pdf_files/'
      Targets:
        - Id: "CampaignDocumentFunctionEvent"
          RoleArn: !GetAtt S3EventRuleRoleNew2.Arn
          Arn: !GetAtt  CampaignDocumentFunction.Arn


  QuestionaireFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: questionaire
      Handler: app.lambda_handler
      CodeUri: src/questionaire/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles campaign questions
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  DocUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: doc-upload
      Handler: app.lambda_handler
      CodeUri: src/doc-upload/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles campaign document upload feature
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName

  RecommendationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: recommendations
      Handler: app.lambda_handler
      CodeUri: src/recommendations/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles campaign cammi recommendations feature
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          LINKEDIN_USER_TABLE: !ImportValue CAMMI-LinkedInUserTableName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          CAMPAIGNS_TABLE: !ImportValue CAMMI-CampaignsTableName

  ContentGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: content
      Handler: app.lambda_handler
      CodeUri: src/content/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles campaign cammi content generator feature
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          CAMPAIGNS_TABLE: !ImportValue CAMMI-CampaignsTableName

  EditRecommendationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: edit-recommendations
      Handler: app.lambda_handler
      CodeUri: src/edit-recommendations/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles editing of campaign cammi recommendations feature
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          LINKEDIN_USER_TABLE: !ImportValue CAMMI-LinkedInUserTableName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          CAMPAIGNS_TABLE: !ImportValue CAMMI-CampaignsTableName

  EditContentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: edit-content
      Handler: app.lambda_handler
      CodeUri: src/edit-content/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles campaign cammi editing in content generator feature
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          CAMPAIGNS_TABLE: !ImportValue CAMMI-CampaignsTableName

  DeleteContentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete-content
      Handler: app.lambda_handler
      CodeUri: src/delete-content/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles campaign cammi deleting in content generator feature
      Role: !ImportValue CAMMI-LambdaRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          CAMPAIGNS_TABLE: !ImportValue CAMMI-CampaignsTableName


Outputs:
  LinkParsingFunctionArn:
    Description: ARN of link parsing Lambda
    Value: !GetAtt LinkParsingFunction.Arn
    Export:
      Name: LinkParsingFunctionArn

  CampaignDocumentFunctionArn:
    Description: ARN of campaign document upload Lambda
    Value: !GetAtt CampaignDocumentFunction.Arn
    Export:
      Name: CampaignDocumentFunctionArn

  QuestionaireFunctionArn:
    Description: ARN of campaign questions Lambda
    Value: !GetAtt QuestionaireFunction.Arn
    Export:
      Name: QuestionaireFunctionArn

  DocUploadFunctionArn:
    Description: ARN of campaign doc upload Lambda
    Value: !GetAtt DocUploadFunction.Arn
    Export:
      Name: DocUploadFunctionArn

  RecommendationsFunctionArn:
    Description: ARN of campaign cammi recommendations Lambda
    Value: !GetAtt RecommendationsFunction.Arn
    Export:
      Name: RecommendationsFunctionArn

  ContentGeneratorFunctionArn:
    Description: ARN of campaign cammi content generator Lambda
    Value: !GetAtt ContentGeneratorFunction.Arn
    Export:
      Name: ContentGeneratorFunctionArn

  EditRecommendationsFunctionArn:
    Description: ARN of editing of campaign cammi recommendations Lambda
    Value: !GetAtt EditRecommendationsFunction.Arn
    Export:
      Name: EditRecommendationsFunctionArn

  EditContentFunctionArn:
    Description: ARN of editing of campaign cammi content Lambda
    Value: !GetAtt EditContentFunction.Arn
    Export:
      Name: EditContentFunctionArn

  DeleteContentFunctionArn:
    Description: ARN of deleting of campaign cammi content Lambda
    Value: !GetAtt DeleteContentFunction.Arn
    Export:
      Name: DeleteContentFunctionArn