AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket stack for CAMMI app

Resources:
  CammiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cammi-devprod
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  Outputs:
    S3BucketName:
      Description: Name of the CAMMI S3 bucket
      Value: !Ref CammiS3Bucket
      Export:
        Name: S3BucketName
  
    S3BucketArn:
      Description: ARN of the CAMMI S3 bucket
      Value: !GetAtt CammiS3Bucket.Arn
      Export:
        Name: S3BucketArn
