AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket stack for CAMMI app

Resources:
  CammiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cammi-devprod
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  CammiBucketName:
    Description: Name of the CAMMI S3 bucket
    Value: !Ref CammiS3Bucket
    Export:
      Name: CAMMI-CammiBucketName
