AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket stack for CAMMI app

Resources:
  CammiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cammi-devprod
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ###################################################
  # Permission for Lambda to be triggered by S3
  ###################################################
  S3LambdaTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue S3LambdaTriggerFunctionArn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt CammiS3Bucket.Arn

  ###################################################
  # S3 Bucket Notification
  ###################################################
  S3BucketNotification:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CammiS3Bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !ImportValue S3LambdaTriggerFunctionArn

Outputs:
  CammiBucketName:
    Description: Name of the CAMMI S3 bucket
    Value: !Ref CammiS3Bucket
    Export:
      Name: CammiBucketName
