AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket stack for CAMMI app

Resources:

  CammiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cammi-devprod
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !ImportValue S3LambdaTriggerFunctionArn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: prompt/businessidea/businessidea/
                  - Name: suffix
                    Value: businessidea.txt

  # Allow S3 to invoke the Lambda
  CammiBucketInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !ImportValue S3LambdaTriggerFunctionArn
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt CammiS3Bucket.Arn


Outputs:
  CammiBucketName:
    Description: Name of the CAMMI S3 bucket
    Value: !Ref CammiS3Bucket
