AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket stack for CAMMI app

Resources:

  CammiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cammi-devprod
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true


  ###################################################
  # S3 Lambda Trigger
  ###################################################
  # S3LambdaTriggerFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: s3-lambda-trigger
  #     Handler: app.lambda_handler
  #     CodeUri: ../document-generation/src/s3-lambda-trigger/
  #     Runtime: python3.13
  #     Timeout: 900
  #     MemorySize: 128
  #     Tracing: Active
  #     Description: This lambda triggers a state machine.
  #     Role: arn:aws:iam::687088702813:role/cammi-lambda-role
  #     Environment:
  #       Variables:
  #         USERS_TABLE: !ImportValue CAMMI-UsersTableName
  #         S3_BUCKET_NAME: !Ref CammiS3Bucket
  #   # -------- S3 Event Trigger (SAM Standard Way) --------
      # Events:
      #   S3UploadEvent:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref CammiS3Bucket
      #       Events: s3:ObjectCreated:* 
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: prefix
      #               Value: prompt/businessidea/businessidea/businessidea.txt       


Outputs:
  CammiBucketName:
    Description: Name of the CAMMI S3 bucket
    Value: !Ref CammiS3Bucket
  
  
  # S3LambdaTriggerFunctionArn:
  #   Description: ARN of S3LambdaTriggerFunction Lambda
  #   Value: !GetAtt S3LambdaTriggerFunction.Arn
  #   Export:
  #     Name: S3LambdaTriggerFunctionArn    
