AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Projects-Organizations feature for CAMMI

Resources:

  AllOrganizationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: all-organizations
      Handler: app.lambda_handler
      CodeUri: src/all-organizations/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles user organizations
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-OrganizationsTableName

  AllProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: all-projects
      Handler: app.lambda_handler
      CodeUri: src/all-projects/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles user projects
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-ProjectsTableName

Outputs:
  AllOrganizationsFunctionArn:
    Description: ARN of all organizations Lambda
    Value: !GetAtt AllOrganizationsFunction.Arn

  AllProjectsFunctionArn:
    Description: ARN of all projects Lambda
    Value: !GetAtt AllProjectsFunction.Arn