AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Projects-Organizations feature for CAMMI

Resources:
  # create project
  CreateProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-project
      Handler: app.lambda_handler
      CodeUri: src/create-project/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles project creation
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-OrganizationsTableName
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName

  # organizations against user
  OrganizationsAgainstUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: organizations-against-user
      Handler: app.lambda_handler
      CodeUri: src/organizations-against-user/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles user-based organizations
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-OrganizationsTableName
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName

  # projects against user
  ProjectsAgainstUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: projects-against-user
      Handler: app.lambda_handler
      CodeUri: src/projects-against-user/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles user-based projects
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-OrganizationsTableName

  # specific organizations
  SpecificOrganizationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: specific-organizations
      Handler: app.lambda_handler
      CodeUri: src/specific-organizations/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles specific organizations
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          ORGANIZATIONS_TABLE: !ImportValue CAMMI-OrganizationsTableName

  # specific projects
  SpecificProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: specific-projects
      Handler: app.lambda_handler
      CodeUri: src/specific-projects/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles specific projects
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          PROJECTS_TABLE: !ImportValue CAMMI-ProjectsTableName

Outputs:
  CreateProjectFunctionArn:
    Description: ARN of CreateProjectFunction Lambda
    Value: !GetAtt CreateProjectFunction.Arn
    Export: 
      Name: CreateProjectFunctionArn    

  OrganizationsAgainstUserFunctionArn:
    Description: ARN of OrganizationsAgainstUserFunction Lambda
    Value: !GetAtt OrganizationsAgainstUserFunction.Arn

  ProjectsAgainstUserFunctionArn:
    Description: ARN of ProjectsAgainstUserFunction Lambda
    Value: !GetAtt ProjectsAgainstUserFunction.Arn

  SpecificOrganizationsFunctionArn:
    Description: ARN of SpecificOrganizationsFunction Lambda
    Value: !GetAtt SpecificOrganizationsFunction.Arn

  SpecificProjectsFunctionArn:
    Description: ARN of SpecificProjectsFunction Lambda
    Value: !GetAtt SpecificProjectsFunction.Arn
