AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Feedback feature for CAMMI

Parameters:
  StageName:
    Type: String
    Default: cammi-mvp
    Description: Deployment stage name for the API

Resources:

  CustomerFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: customer-feedback
      Handler: customer-feedback.lambda_handler
      CodeUri: src/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles customer feedback submission
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          USERS_FEEDBACK_TABLE: !ImportValue CAMMI-UsersFeedbackTableName

  CheckCustomerFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: check-customer-feedback
      Handler: check-customer-feedback.lambda_handler
      CodeUri: src/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Fetches and checks existing customer feedback
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE: !ImportValue CAMMI-UsersTableName
          USERS_FEEDBACK_TABLE: !ImportValue CAMMI-UsersFeedbackTableName

Outputs:
  CustomerFeedbackFunctionArn:
    Description: ARN of CustomerFeedback Lambda
    Value: !GetAtt CustomerFeedbackFunction.Arn

  CheckCustomerFeedbackFunctionArn:
    Description: ARN of CheckCustomerFeedback Lambda
    Value: !GetAtt CheckCustomerFeedbackFunction.Arn
