AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Payment Gateway feature for CAMMI


Resources:
  PaymentGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: payment-gateway-lambda
      Handler: app.lambda_handler
      CodeUri: src/payment-gateway-lambda/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles payment processing for CAMMI
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          STRIPE_API_KEY: "{{resolve:secretsmanager:cammi-secrets:SecretString:STRIPE_API_KEY}}"
          STRIPE_TABLE_NAME: !ImportValue CAMMI-StripeTableName

  StripeUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stripe-users
      Handler: app.lambda_handler
      CodeUri: src/stripe-users/
      Runtime: python3.13
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Description: Handles Stripe Users for CAMMI
      Role: arn:aws:iam::687088702813:role/cammi-lambda-role
      Environment:
        Variables:
          USERS_TABLE_NAME: !ImportValue CAMMI-UsersTableName
          STRIPE_TABLE_NAME: !ImportValue CAMMI-StripeTableName          


Outputs:
  PaymentGatewayFunctionArn:
    Description: ARN of payment gateway Lambda
    Value: !GetAtt PaymentGatewayFunction.Arn
  StripeUsersFunctionArn:
    Description: ARN of Stripe Users Function Lambda
    Value: !GetAtt StripeUsersFunction.Arn
