name: CAMMI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy SAM App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.116.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::687088702813:role/CICD-SAM-CAMMI
          aws-region: us-east-1

      - name: Build SAM application
        run: sam build --template-file template.yaml

      - name: Deploy SAM application
        run: sam deploy --template-file template.yaml --no-confirm-changeset --no-fail-on-empty-changeset
